### PR TITLE
fix: ensure .Swarm.ConnMgr exists before accessing

### LINKED ISSUE #2254: TypeError: Cannot destructure property 'GracePeriod' of 'config.Swarm.Co
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.23.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
TypeError: Cannot destructure property 'GracePeriod' of 'config.Swarm.ConnMgr' as it is undefined.
    at migrateConfig (C:\Users\TIK\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\config.js:209:13)
    at getIpfsd (C:\Users\TIK\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:56:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startDaemon (C:\Users\TIK\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:210:17)
    at async startIpfs (C:\Users\TIK\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:48:17)
    at async setupDaemon (C:\Users\TIK\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:3)
    at async run (C:\Users\TIK\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\index.js:85:5)
```

### PR DESCRIPTION
**Pull request by hacdias**
Fixes #2254 by adding a simple check to make sure `.Swarm.ConnMgr` actually exists in the configuration before changing it.

I thought about adding a test case for this, but then I would also have to add one for all the remaining migrations. However, I think that would almost duplicate the E2E time testing.

### CODE REVIEW

File: src/daemon/config.js [hunk 1]
```diff
@@ -205,19 +205,21 @@ function migrateConfig (ipfsd) {
...
-    if (LowWater > 20) {
-      config.Swarm.ConnMgr.LowWater = 20
-      changed = true
-    }
-    if (HighWater > 40) {
-      config.Swarm.ConnMgr.HighWater = 40
-      changed = true
+    if (config.Swarm && config.Swarm.ConnMgr) {
+      // lower ConnMgr https://github.com/ipfs/ipfs-desktop/issues/2039
+      const { GracePeriod, LowWater, HighWater } = config.Swarm.ConnMgr
```
Comment (SgtPooki) [inline src/daemon/config.js:210]: If these values are not defined, we should handle that usecase. If they're not defined, we shouldn't define them. An escape hatch here could be useful

**Review by SgtPooki — APPROVED** [review]
