### PR TITLE
fix: i18n init done fires even with lang load error

### LINKED ISSUE #2627: Taskbar icon not working
- OS: Windows 10 x64
- Version of IPFS Desktop: [0.30.2](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.30.2)

**Describe the bug**
I'm unable to right-click on the IPFS icon on the taskbar to quit the application. No menu appears. I'm only able to open the GUI with left-click!

**To Reproduce**
1. Start IPFS
2. Right-click on the icon on the taskbar
3. Nothing happens!

**Expected behavior**
Menu with options should appear!

**Screenshots**
---

**Additional context**
The icon also don't change color when I'm connected!
The version [0.30.1](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.30.1) works fine!

[combined.log](https://github.com/ipfs/ipfs-desktop/files/12604517/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/12604519/error.log)

Thanks

### PR DESCRIPTION
**Pull request by SgtPooki**
i18next has some auto-magical loading of translation files that kicks
off loading multiple languages (e.g. 'en', 'en-US', 'en-UK', etc.) but
we don't have all of those files for IPFS-Desktop. i18next.init
will fire an error if any of those files fail to load, even if one
succeeds.

This fix ensures that `i18n.initDone` is set on context even if we see
an error.

fixes #2627

### CODE REVIEW

File: src/i18n.js [hunk 1]
```diff
@@ -29,8 +31,14 @@ module.exports = async function () {
...
-        logger.error('[i18n] init failed', err)
-        return
+        /**
+         * even if an error occurs here, i18n still may work properly.
+         * e.g. https://github.com/ipfs/ipfs-desktop/issues/2627
+         * Language's of "en-US" or "zh" may not exist at `join(__dirname, '../assets/locales/{{lng}}.json')` but i18next loads
+         * the appropriate language file with/without the region code. Partially discussed at https://github.com/i18next/i18next/issues/964
+         */
+        logger.error('[i18n] init error')
+        logger.error(err)
```
Comment (SgtPooki) [inline src/i18n.js:41]: the actual Error was not being logged for some reason... error files and logging patterns need a serious look
